### PR TITLE
Feature/dynamic page by markdown

### PR DESCRIPTION
**Pull request by mziescha**
Able to load markdown for dynamic github page

### CODE REVIEW

**Comment by sonntagd** [comment]
@renormalist Das ist das, was wir mal als Idee hatten, aber nicht umsetzen konnten: Inhalte als Markdown ablegen. In diesem Fall wird es dann per JavaScript in HTML gewandelt und angezeigt. Also einfach zu nutzen.

**Comment by rurban** [comment]
Is there a no-script fallback? Like a link to the .md at least.
Or offline md -> html conversion.

**Comment by sonntagd** [comment]
Offline MD->HTML would be possible, but the goal was to have a very handy solution where you only have to edit the md file and commit it.

Maybe it would be okay to include a link to the index.md as fallback.

**Comment by sonntagd** [comment]
What about having a webhook that is called everytime new content is pushed. There is a small app that checks out the repo, runs a perl script to perform the markdown to html conversion and pushs its changes back to the repo.

**Comment by sonntagd** [comment]
This conversion could be done via Travis as part of a build process, so no external software installation or separate server is needed.

**Comment by sonntagd** [comment]
We implemented this idea tonight on the master branch and it works :-)

**Comment by renormalist** [comment]
Hammer! Ich fasse es nicht! Coole Sache.

**Pull request closed without merging**
